apiVersion: v1
kind: Service
metadata:
  name: todolist-nodeport-service
  namespace: todoapp
spec:
  type: NodePort
  selector:
    app: todolist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008